name: Publish package

on:
  push:
    tags:
      - "*.*.*"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  github-release:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: 11tyAutoCacheBuster.js

  npm-publish:
    runs-on: ubuntu-latest
    # See https://docs.npmjs.com/trusted-publishers#github-actions-configuration
    permissions:
      id-token: write
      contents: read
    needs: [test]
    steps:
      - uses: actions/checkout@v6
      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install
      - run: npm publish
