name: Run tests

on: [push, pull_request, workflow_call]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [20, 22, 24]
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.version }}

      - run: yarn install --immutable 
      - run: yarn test
